'use client';

import Link from 'next/link';
import { motion, animate, useMotionValue } from 'motion/react';
import { Share2, Handshake, BadgeDollarSign } from 'lucide-react';
import { useState, useEffect, useRef } from 'react';

// ─── Data ─────────────────────────────────────────────────────────────────────

const steps = [
  {
    num: '01',
    icon: Share2,
    title: 'Share Your Link',
    desc: 'Grab your unique referral link from your dashboard and share it with your founder friends or clients looking to build a website.',
  },
  {
    num: '02',
    icon: Handshake,
    title: 'We Close the Deal',
    desc: 'Our technical team hops on a discovery call with your lead, builds the perfect project scope, and completes their successful onboarding.',
  },
  {
    num: '03',
    icon: BadgeDollarSign,
    title: 'Get Reward For Your Leads',
    desc: 'As the client clears project milestone payments, your 5% commission share of the total payment is automatically calculated and credited to your account.',
  },
];

const policy = [
  {
    title: 'Overview',
    body: 'The Zonet Refer & Earn Program allows people to monetise their professional network by introducing businesses, founders, or individuals in need of premium technical services. By participating, you agree to fulfil the criteria outlined below to qualify for a referral reward.',
  },
  {
    title: 'Eligibility & Tracking',
    items: [
      { label: 'Active Account', text: 'Referrals must have a registered and verified profile on our platform to generate unique tracking links and receive payouts.' },
      { label: 'Session Validity', text: 'Referral profit shares will be tracked and credited only if the client completes their project inquiry or booking during the same session after clicking your referral link, without navigating away or visiting other competitor platforms before scheduling their discovery call.' },
      { label: 'Lead Registration', text: 'If a unique tracking link is not used, the referred client must explicitly name you as their referrer during their initial discovery call with the Zonet team to qualify.' },
      { label: 'Self-Referrals', text: 'If you are the one who needs to build a website for your business, then you are most welcome by team Zonet — we will provide you with a fair share of discount on your final payment.' },
    ],
  },
  {
    title: 'Qualification & Reward Structure',
    items: [
      { label: 'Successful Payment Requirement', text: 'Profit will be credited only after your client\'s successful payment with Zonet. A referral is officially active only when the client has signed the formal service contract and their initial deposit has successfully cleared.' },
      { label: 'Earning Percentage', text: 'You will get 5% of the profit from the overall payment for your client\'s project.' },
      { label: 'Net Profit Calculation', text: 'The 5% reward is calculated strictly from the final net profit generated by the agreed-upon project scope. This explicitly excludes third-party tool subscriptions, external API licenses, domain registrations, or cloud hosting infrastructure fees (e.g., AWS, Google Cloud).' },
      { label: 'Milestone-Based Payouts', text: 'Your 5% profit share will be credited to your account in instalments as the client clears each project milestone payment, rather than as a single lump sum upfront.' },
    ],
  },
  {
    title: 'Project Discontinuation & Timeline Rules',
    items: [
      { label: 'Project Discontinuation', text: 'No profit will be shared after discontinuation of the client\'s project. If a client terminates or cancels their contract midway, referral payouts will immediately cease, and no future milestones will be eligible for profit sharing.' },
      { label: 'Timeline Extensions', text: 'Delays caused by a lack of feedback or delayed assets from the client\'s side will extend the delivery window. Zonet is not liable for delayed milestones due to client dependencies, and referral payouts will shift accordingly based on actual completion dates.' },
    ],
  },
  {
    title: 'Program Restrictions & Fair Play',
    body: 'Zonet reserves the right to modify, pause, or terminate the Refer & Earn program structure at any time. Any active, onboarded projects at the time of modification will be honoured under the terms agreed upon during onboarding.',
  },
];

// ─── Presets ──────────────────────────────────────────────────────────────────

const presets = [
  { label: '₹50K', value: 50000 },
  { label: '₹1L', value: 100000 },
  { label: '₹2L', value: 200000 },
  { label: '₹5L', value: 500000 },
  { label: '₹10L', value: 1000000 },
];

const COMMISSION = 0.05;
const MIN = 10000;
const MAX = 2000000;

function formatINR(n: number) {
  if (n >= 100000) return `₹${(n / 100000).toFixed(n % 100000 === 0 ? 0 : 1)}L`;
  if (n >= 1000) return `₹${(n / 1000).toFixed(0)}K`;
  return `₹${n}`;
}

function AnimatedNumber({ value }: { value: number }) {
  const motionVal = useMotionValue(value);
  const [display, setDisplay] = useState(value);
  const prevRef = useRef(value);

  useEffect(() => {
    const ctrl = animate(prevRef.current, value, {
      duration: 0.5,
      ease: 'easeOut',
      onUpdate: (v) => setDisplay(Math.round(v)),
    });
    prevRef.current = value;
    return () => ctrl.stop();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [value]);

  // keep motionVal in sync to avoid lint warning
  useEffect(() => { motionVal.set(value); }, [value, motionVal]);

  return <>{display.toLocaleString('en-IN')}</>;
}

// ─── Calculator ───────────────────────────────────────────────────────────────

function CommissionCalculator() {
  const [dealValue, setDealValue] = useState(200000);
  const commission = Math.round(dealValue * COMMISSION);
  const pct = ((dealValue - MIN) / (MAX - MIN)) * 100;

  return (
    <div className="bg-white rounded-3xl border border-[#E6E4DF] p-8 shadow-[0_20px_60px_rgba(0,0,0,0.08)]">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <div className="text-[0.65rem] font-bold uppercase tracking-[2px] text-[#E8C547] mb-1">Live Calculator</div>
          <div className="text-[1rem] font-extrabold text-[#1a1a1a]">See what you&apos;ll earn</div>
        </div>
        <div className="w-10 h-10 rounded-xl bg-[#E8C547]/10 border border-[#E8C547]/25 flex items-center justify-center">
          <BadgeDollarSign size={20} className="text-[#E8C547]" strokeWidth={1.5} />
        </div>
      </div>

      {/* Deal value row */}
      <div className="flex justify-between items-center mb-3">
        <span className="text-[0.78rem] font-semibold text-[#6b6b6b]">Deal Value</span>
        <span className="text-[1.1rem] font-black text-[#1a1a1a]">{formatINR(dealValue)}</span>
      </div>

      {/* Slider */}
      <div className="relative h-2 rounded-full bg-[#F0EDE6] mb-2">
        <div className="absolute inset-y-0 left-0 rounded-full bg-[#E8C547]" style={{ width: `${pct}%` }} />
        <input
          type="range" min={MIN} max={MAX} step={10000} value={dealValue}
          onChange={(e) => setDealValue(Number(e.target.value))}
          className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
        />
        <div
          className="absolute top-1/2 -translate-y-1/2 -translate-x-1/2 w-5 h-5 rounded-full bg-[#E8C547] border-[3px] border-white shadow-md pointer-events-none"
          style={{ left: `${pct}%` }}
        />
      </div>
      <div className="flex justify-between text-[0.62rem] text-[#aaa] font-medium mb-5">
        <span>₹10K</span><span>₹20L</span>
      </div>

      {/* Presets */}
      <div className="flex flex-wrap gap-2 mb-6">
        {presets.map((p) => (
          <button
            key={p.value}
            onClick={() => setDealValue(p.value)}
            className={`px-3.5 py-1.5 rounded-full text-[0.72rem] font-bold border transition-all duration-150 ${
              dealValue === p.value
                ? 'bg-[#1a1a1a] text-white border-[#1a1a1a]'
                : 'bg-transparent text-[#6b6b6b] border-[#E6E4DF] hover:border-[#1a1a1a] hover:text-[#1a1a1a]'
            }`}
          >
            {p.label}
          </button>
        ))}
      </div>

      {/* Result */}
      <div className="bg-[#111111] rounded-2xl p-6 mb-4">
        <div className="text-[0.65rem] font-bold uppercase tracking-[2px] text-[#888] mb-1">You Earn</div>
        <div className="text-[3rem] font-black text-[#E8C547] leading-none tracking-tight">
          ₹<AnimatedNumber value={commission} />
        </div>
        <div className="text-[0.72rem] text-[#666] mt-2">5% of ₹{dealValue.toLocaleString('en-IN')} contract value</div>
      </div>

      {/* Mini breakdown */}
      <div className="grid grid-cols-2 gap-3 mb-4">
        <div className="bg-[#faf8f5] border border-[#E6E4DF] rounded-xl p-3 text-center">
          <div className="text-[0.6rem] font-bold uppercase tracking-[1.5px] text-[#aaa] mb-1">Deal Value</div>
          <div className="text-[1rem] font-black text-[#1a1a1a]">₹<AnimatedNumber value={dealValue} /></div>
        </div>
        <div className="bg-[#faf8f5] border border-[#E6E4DF] rounded-xl p-3 text-center">
          <div className="text-[0.6rem] font-bold uppercase tracking-[1.5px] text-[#aaa] mb-1">Rate</div>
          <div className="text-[1rem] font-black text-[#E8C547]">5%</div>
        </div>
      </div>

      <Link
        href="/contact"
        className="w-full flex items-center justify-center gap-2 bg-[#E8C547] text-[#1a1a1a] text-[0.875rem] font-bold py-3.5 rounded-xl hover:-translate-y-0.5 hover:shadow-[0_8px_24px_rgba(232,197,71,0.35)] transition-all duration-200"
      >
        Start Referring Now →
      </Link>
    </div>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function ReferEarnPage() {
  return (
    <div className="bg-[#faf8f5] min-h-screen">

      {/* ── HERO ── */}
      <section className="pt-24 pb-16 px-6 relative overflow-hidden">
        <div
          className="absolute inset-0 pointer-events-none"
          style={{
            backgroundImage: 'linear-gradient(rgba(232,197,71,0.06) 1px, transparent 1px), linear-gradient(90deg, rgba(232,197,71,0.06) 1px, transparent 1px)',
            backgroundSize: '40px 40px',
          }}
        />
        <div className="relative max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">

          {/* Left — copy */}
          <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.5 }}>
            <span className="inline-flex items-center gap-2 border border-[#E8C547]/50 bg-[#E8C547]/10 rounded-full px-4 py-1.5 text-[0.7rem] font-bold tracking-[2px] uppercase text-[#b08a00] mb-6">
              <span className="w-1.5 h-1.5 rounded-full bg-[#E8C547] inline-block" />
              Refer &amp; Earn
            </span>

            <h1 className="text-[clamp(2.4rem,4.5vw,3.8rem)] font-extrabold leading-[1.07] tracking-[-2px] text-[#0e0e0e] mb-5" style={{ fontFamily: 'Sora, sans-serif' }}>
              Just Building<br />Connection Is<br />
              <span className="text-[#E8C547]">Not Enough.</span>
            </h1>

            <p className="text-[1rem] text-[#6b6b6b] leading-[1.7] max-w-96 mb-8">
              Refer Zonet to your connections and earn a{' '}
              <strong className="text-[#1a1a1a] font-bold">5% commission</strong> on every successful contract — paid milestone by milestone.
            </p>

            <Link
              href="/contact"
              className="inline-flex items-center gap-2 bg-[#E8C547] text-[#1a1a1a] text-[0.875rem] font-bold px-8 py-3.5 rounded-full hover:bg-[#d4b038] hover:-translate-y-px transition-all duration-200"
            >
              Connect &amp; Start Earning →
            </Link>
          </motion.div>

          {/* Right — calculator */}
          <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.5, delay: 0.1 }}>
            <CommissionCalculator />
          </motion.div>

        </div>
      </section>

      {/* ── HOW IT WORKS ── */}
      <section className="py-16 lg:py-24 px-6 bg-[#faf8f5]">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-14">
            <div className="text-[0.68rem] font-bold uppercase tracking-[2px] text-[#E8C547] mb-3">How It Works</div>
            <h2 className="text-[clamp(1.8rem,3.5vw,2.6rem)] font-extrabold tracking-[-1.5px] text-[#1a1a1a] leading-[1.1]">
              How To Earn Commission
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {steps.map((step, i) => (
              <motion.div
                key={step.num}
                className="relative bg-white rounded-2xl border border-[#E6E4DF] p-8 flex flex-col gap-5 hover:shadow-lg hover:-translate-y-1 transition-all duration-200"
                initial={{ opacity: 0, y: 24 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1, duration: 0.5 }}
              >
                <div className="flex items-start justify-between">
                  <div className="w-12 h-12 rounded-xl bg-[#E8C547]/10 border border-[#E8C547]/25 flex items-center justify-center">
                    <step.icon size={22} className="text-[#E8C547]" strokeWidth={1.5} />
                  </div>
                  <span className="text-[2rem] font-black text-[#E8C547]/15 leading-none">{step.num}</span>
                </div>
                <div>
                  <h3 className="text-[1.05rem] font-extrabold text-[#1a1a1a] mb-2">{step.title}</h3>
                  <p className="text-[0.85rem] text-[#6b6b6b] leading-[1.7]">{step.desc}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── POLICY ── */}
      <section id="policy" className="py-16 lg:py-24 px-6 bg-[#faf8f5]">
        <div className="max-w-3xl mx-auto">

          <div className="mb-8 text-center">
            <div className="text-[0.68rem] font-bold uppercase tracking-[2px] text-[#E8C547] mb-3">Legal</div>
            <h2 className="text-[clamp(1.8rem,3.5vw,2.4rem)] font-extrabold tracking-[-1.5px] text-[#1a1a1a] leading-[1.1]">
              Refer &amp; Earn Policy
            </h2>
          </div>

          {/* Document box */}
          <div className="bg-white border border-[#D6D1C4] rounded-2xl shadow-[0_4px_24px_rgba(0,0,0,0.06)] overflow-hidden">

            {/* Document header bar */}
            <div className="bg-[#F5F2EA] border-b border-[#D6D1C4] px-8 py-5 flex items-center justify-between">
              <div>
                <div className="text-[0.7rem] font-bold uppercase tracking-[2px] text-[#9A8F7A] mb-0.5">Official Program Document</div>
                <div className="text-[0.875rem] font-bold text-[#1a1a1a]">Zonet Refer &amp; Earn — Terms &amp; Conditions</div>
              </div>
              <div className="hidden sm:flex items-center gap-2 text-[0.65rem] font-semibold text-[#9A8F7A] border border-[#D6D1C4] rounded-full px-3 py-1.5 bg-white">
                <span className="w-1.5 h-1.5 rounded-full bg-[#E8C547] inline-block" />
                Effective: 2025
              </div>
            </div>

            {/* Scrollable body */}
            <div className="h-[520px] overflow-y-auto px-8 py-8 scroll-smooth" style={{ fontFamily: 'Georgia, "Times New Roman", serif' }}>
              {policy.map((section, i) => (
                <div key={i} className={i < policy.length - 1 ? 'mb-9 pb-9 border-b border-[#EAE6DC]' : ''}>

                  <h3 className="text-[0.75rem] font-bold uppercase tracking-[1.5px] text-[#9A8F7A] mb-1" style={{ fontFamily: 'Inter, sans-serif' }}>
                    Section {i + 1}
                  </h3>
                  <h4 className="text-[1.05rem] font-bold text-[#1a1a1a] mb-4" style={{ fontFamily: 'Inter, sans-serif' }}>
                    {section.title}
                  </h4>

                  {'body' in section && section.body && (
                    <p className="text-[0.9rem] text-[#4a4540] leading-[1.85]">{section.body}</p>
                  )}

                  {'items' in section && section.items && (
                    <div className="flex flex-col gap-4">
                      {section.items.map((item, j) => (
                        <div key={j} className="flex gap-4">
                          <div className="mt-1 w-5 h-5 rounded flex-shrink-0 bg-[#F5F2EA] border border-[#D6D1C4] flex items-center justify-center text-[0.55rem] font-black text-[#9A8F7A]" style={{ fontFamily: 'Inter, sans-serif' }}>
                            {j + 1}
                          </div>
                          <p className="text-[0.9rem] text-[#4a4540] leading-[1.85]">
                            <strong className="text-[#1a1a1a] font-semibold" style={{ fontFamily: 'Inter, sans-serif' }}>{item.label}:</strong>{' '}
                            {item.text}
                          </p>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              ))}

              {/* Footer stamp */}
              <div className="mt-8 pt-6 border-t border-[#EAE6DC] flex items-center justify-between">
                <span className="text-[0.7rem] text-[#9A8F7A]" style={{ fontFamily: 'Inter, sans-serif' }}>© {new Date().getFullYear()} Zonet. All rights reserved.</span>
                <span className="text-[0.7rem] text-[#9A8F7A] border border-[#D6D1C4] rounded px-2 py-0.5" style={{ fontFamily: 'Inter, sans-serif' }}>v1.0</span>
              </div>
            </div>

          </div>
        </div>
      </section>

    </div>
  );
}
